---
title: "Roger's code"
output: html_notebook
---

```{r}
#Emails from Emilio and Roger

#17.02.2020

#Dear Emilio,

#One of my group (Zuzanna, you might have met her when we were working in Vigo) has some mating data for L saxatilis and Larcana. We were hoping to analyse them with Jmating but I am not sure that it can handle our experiment so we would value your advice. The design was 'no-choice', i.e. one male and one female per trial. The unusual thing is that we could not identify the snail species in advance (they have been identified genetically, after the mating trials). This means that the numbers in the four categories (AA, AS, SA, SS, female:male) are unbalanced. Normally, in Jmating, one gives the total numbers of male A, male S, female A and female S and then the numbers of mating in the four possible combinations but I think this assumes balance. We really want to work from the numbers of trials in each of the 4 categories and the numbers of successes. Is that possible with Jmating?

#Nice (form our perspective) that you are thinking to use JMATING, of course you can ask at any moment about this and similar topics, actually you can suggest Suzzane to contact me directly if she has any further doubt about JMATING or similar. Of course that a balancing design should be followed (regarding the number of attempts of each type at the start of the experiment). In fact, a no-choice design should be the most sensitive a priori for any unbalancing design, but it depends of the magnitude of unbalancing problem. For example, imagine that you place the following attempts of each of the four classes: 30 10 10 30 If all attempts produce mating you would be under a true case of random mating, but will obtain a significant IPSS of 0.5 under bootstrapping. In this case, the unbalancing design works against your hypothesis and should be not analysed.

#However, if your design show any unbalance in the opposite direction

#15 19 16 15

#and you still find a significant IPSS after the experiment

#15 2 1 14

#That would produce a valid results that is biologically relevant and so (IPSI=0.8 and significant), depending of each particular case you could use safely certain unbalanced designs... So, in summary, unbalanced designs are risky (like heterocedasticity) but you need to check case by case if they could be still useful.

#Related to this, We have been using different mate choice experiments in Echinolittorina last summer, with excellent results. We compared male-choice, no-choice and multiple choice designs. I would admit (unpublished results yet) that clearly mate choice outperfomed the others (absolutely!). So one of our recommendations will be to use multiple choice instead of the other designs (especially if the species, like littorinids, do show multiple choice in the wild). I know of the potential problems of absence of independence, but we are biologist not statisticians, and so the biological perspective should be the priority. I will share the MS with you if you are interested as soon as we have a final complete version (a couple of months?).

#Hi Zuzanna,

#Here is Emilio's reply. I have done a quick R script (attached) that does the basic Jmating calculations. It also down-samples so that all combinations of male and female have the same sample size. This shows that the I_psi statistic is not biased: the distribution of down-sampled permutations is centred on the I_psi value for the full data set. I am actually not so sure that other estimators (PSS and PTI) are unbiased but I have not checked that yet. If they are, it is not really a problem because we can use the mean of the down-sampled estimates. I guess we can also add a bootstrap to this script, if necessary, to get a confidence interval on I_psi.


```

#### WALES ####

```{r}
# total all

# mat_mact	ARC__ARC	26		
# mat_mact	ARC__SAX	6		
# mat_mact	SAX__ARC	3		
# mat_mact	SAX__SAX	16		
# not_mated_mact	ARC__ARC	66		total: 66+26 = 92
# not_mated_mact	ARC__SAX	168		total: 168+6 = 174
# not_mated_mact	SAX__ARC	127		total: 127+3 = 130
# not_mated_mact	SAX__SAX	233	  total: 233+16 = 239

rm(list=ls())

total <- c(92,174,130,239)
mate <- c(26,6,3,16)
fem <- c("A","A","S","S")
mal <- c("A","S","A","S")

matlm <- glm(cbind(mate,total-mate)~fem+mal,
             family=binomial(link=logit))

print("Summary matlm")
print(summary(matlm))
print("ANOVA matlm")
print(anova(matlm))
print("Fitted(matlm)*total")
print(fitted(matlm)*total)

# Jmating like calculations

Jmate <- function(tot,mat){
  t <- sum(mat)
  TT <- sum(tot)
  Am <- tot[1]+tot[3]
  Af <- tot[1]+tot[2]
  Bm <- tot[2]+tot[4]
  Bf <- tot[3]+tot[4]
  S <- Am*Af+Am*Bf+Bm*Af+Bm*Bf
  AB <- c(Af*Af,Af*Bm,Bf*Am,Bf*Bm)

  PTI <- (mat*S)/(t*AB)
  PSI <- (mat*t)/((mat[c(1,1,1,3)]+mat[c(2,2,3,4)])*(mat[c(1,2,3,2)]+mat[c(3,4,4,4)]))
  PSS <- ((mat[c(1,1,1,3)]+mat[c(2,2,3,4)])*(mat[c(1,2,3,2)]+mat[c(3,4,4,4)])*S)/(t^2*AB)

  I_psi <- (PSI[1]+PSI[4]-PSI[2]-PSI[3])/sum(PSI)
  
  return(l = list(PSI,PSS,I_psi))
}


print("Pair total index (PTI = PSS x PSI) is the number of observed pair types divided by the expected pair types from total numbers and measures the combined effects of both sexual selection and sexual isolation. - however, it does not return that value")

print ("Pair sexual selection (PSS) is the statistic obtained when the expected pair types from mates is divided by the expected pair types from total numbers. Because both expected pair types were calculated assuming full random mating, PSS only measures the sexual selective differences between copulating and noncopulating samples for every pair type, that is, the effect of sexual selection")

print("Pair sexual isolation (PSI) is defined for every pair combination as the number of observed pair types divided by the expected pair types from mates. This statistic compares the observed pairs with the expected pairs from mating individuals (assuming random mating), so it is a measure of sexual isolation effects.")

print("I_psi - joint isolation index is used with PSI statistics (IPSI). I_psi <- (PSI[1]+PSI[4]-PSI[2]-PSI[3])/sum(PSI)")

print("list(PSI,PSS,I_psi), PSS - pair sexual selection, PSI - pair sexual isolation")

print(Jmate(total,mate))


#downsample to minimum of total for all combinations

AA <- c(rep(0,total[1]-mate[1]),rep(1,mate[1]))
AS <- c(rep(0,total[2]-mate[2]),rep(1,mate[2]))
SA <- c(rep(0,total[3]-mate[3]),rep(1,mate[3]))
SS <- c(rep(0,total[4]-mate[4]),rep(1,mate[4]))

Ipsi_ds <- rep(NA,100)

for (i in 1:100){
  AAr <- AA[order(runif(length(AA)))]
  ASr <- AS[order(runif(length(AS)))]
  SAr <- SA[order(runif(length(SA)))]
  SSr <- SS[order(runif(length(SS)))]
  totds <- rep(min(total),4)
  matds <- c(sum(AAr[1:min(total)]),sum(ASr[1:min(total)]),sum(SAr[1:min(total)]),sum(SSr[1:min(total)]))
  
  Ipsi_ds[i] <- Jmate(totds,matds)[[3]]
}

hist(Ipsi_ds)
hist(Ipsi_ds, xlim=c(0,1))

```



### ENGLAND ###
```{r}

# total all

# mat_mact	ARC__ARC	48		
# mat_mact	ARC__SAX	7	
# mat_mact	SAX__ARC	12	
# mat_mact	SAX__SAX	45		
# not_mated_mact	ARC__ARC	99		total: 99+48 = 147
# not_mated_mact	ARC__SAX	166		total: 166+7 = 173
# not_mated_mact	SAX__ARC	201		total: 201+12 = 213
# not_mated_mact	SAX__SAX	380	  total: 380+45 = 425

rm(list=ls())

total <- c(147,173,213,425)
mate <- c(48,7,12,45)
fem <- c("A","A","S","S")
mal <- c("A","S","A","S")

matlm <- glm(cbind(mate,total-mate)~fem+mal,
             family=binomial(link=logit))

print("Summary matlm")
print(summary(matlm))
print("ANOVA matlm")
print(anova(matlm))
print("Fitted(matlm)*total")
print(fitted(matlm)*total)

# Jmating like calculations

Jmate <- function(tot,mat){
  t <- sum(mat)
  TT <- sum(tot)
  Am <- tot[1]+tot[3]
  Af <- tot[1]+tot[2]
  Bm <- tot[2]+tot[4]
  Bf <- tot[3]+tot[4]
  S <- Am*Af+Am*Bf+Bm*Af+Bm*Bf
  AB <- c(Af*Af,Af*Bm,Bf*Am,Bf*Bm)

  PTI <- (mat*S)/(t*AB)
  PSI <- (mat*t)/((mat[c(1,1,1,3)]+mat[c(2,2,3,4)])*(mat[c(1,2,3,2)]+mat[c(3,4,4,4)]))
  PSS <- ((mat[c(1,1,1,3)]+mat[c(2,2,3,4)])*(mat[c(1,2,3,2)]+mat[c(3,4,4,4)])*S)/(t^2*AB)

  I_psi <- (PSI[1]+PSI[4]-PSI[2]-PSI[3])/sum(PSI)
  
  return(l = list(PSI,PSS,I_psi))
}

print("list(PSI,PSS,I_psi), PSS - pair sexual selection, PSI - pair sexual isolation")

print("Pair total index (PTI = PSS x PSI) is the number of observed pair types divided by the expected pair types from total numbers and measures the combined effects of both sexual selection and sexual isolation. - however, it does not return that value")

print ("Pair sexual selection (PSS) is the statistic obtained when the expected pair types from mates is divided by the expected pair types from total numbers. Because both expected pair types were calculated assuming full random mating, PSS only measures the sexual selective differences between copulating and noncopulating samples for every pair type, that is, the effect of sexual selection")

print("Pair sexual isolation (PSI) is defined for every pair combination as the number of observed pair types divided by the expected pair types from mates. This statistic compares the observed pairs with the expected pairs from mating individuals (assuming random mating), so it is a measure of sexual isolation effects.")

print("I_psi - joint isolation index is used with PSI statistics (IPSI). I_psi <- (PSI[1]+PSI[4]-PSI[2]-PSI[3])/sum(PSI)")

print(Jmate(total,mate))


#downsample to minimum of total for all combinations

AA <- c(rep(0,total[1]-mate[1]),rep(1,mate[1]))
AS <- c(rep(0,total[2]-mate[2]),rep(1,mate[2]))
SA <- c(rep(0,total[3]-mate[3]),rep(1,mate[3]))
SS <- c(rep(0,total[4]-mate[4]),rep(1,mate[4]))

Ipsi_ds <- rep(NA,100)

for (i in 1:100){
  AAr <- AA[order(runif(length(AA)))]
  ASr <- AS[order(runif(length(AS)))]
  SAr <- SA[order(runif(length(SA)))]
  SSr <- SS[order(runif(length(SS)))]
  totds <- rep(min(total),4)
  matds <- c(sum(AAr[1:min(total)]),sum(ASr[1:min(total)]),sum(SAr[1:min(total)]),sum(SSr[1:min(total)]))
  
  Ipsi_ds[i] <- Jmate(totds,matds)[[3]]
}

hist(Ipsi_ds)
hist(Ipsi_ds, xlim=c(0,1))

```
